on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

name: linting and testing

jobs:
  test:
    name: Automatic linting and testing
    runs-on: ubuntu-latest

    container:
      image: python:3.8.16-buster

    steps:
      - uses: actions/checkout@v2

      - name: Setup Poetry 1.4.2
        run: pip install poetry==1.4.2

      - name: Check pyproject.toml
        run: poetry check

      - name: Install python dependencies with Poetry
        run: poetry install

      - name: Check files with isort
        run: poetry run isort . --check

      - name: Check files with Black
        run: poetry run black . --check

      - name: Lint files with flake8
        run: poetry run flake8

      - name: Run tests
        run: poetry run pytest
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
